### ISSUE TITLE
Create an icon

### ISSUE THREAD

**Issue by PhilippRigoll** [PhilippRigoll/osmapy#12]
Create a Icon for POSM

**Comment by thefeiter** [comment]
I imagine some combination of Python and OSM icons would do...
Something like this:
![appicon](https://user-images.githubusercontent.com/46082330/83950035-fc66ae00-a827-11ea-8551-072b162227e9.png)

**Comment by PhilippRigoll** [comment]
I like it! 👍  But I am a bit conserend about the use of the python logo. I'm not sure if we are allowed to use it. Maybe we have to draw something on our own.
But we can use the OSM logo as a starting point. I think this should be allowed: [https://wiki.osmfoundation.org/wiki/Trademark_Policy#3.5._Use_of_remixed_logos](https://wiki.osmfoundation.org/wiki/Trademark_Policy#3.5._Use_of_remixed_logos).

**Comment by thefeiter** [comment]
I just tried to find out about the usage of the Python Logo [here](https://www.python.org/psf/trademarks/). And just decided to write an E-Mail to [PSF-Trademarks](mailto:psf-trademarks@python.org) asking for a clarification if something like my draft would be ok.

**Comment by thefeiter** [comment]
Here is the answer:

Hi,

changes to the logo outline are not permitted, so you'd either have to place the additional graphics completely inside the two snakes or completely outside.

Thanks,

**Comment by thefeiter** [comment]
![Icon suggestion v1](https://user-images.githubusercontent.com/46082330/83963137-f2829080-a8a3-11ea-8476-09580ccab14a.png)

Maybe something like that?

**Comment by thefeiter** [comment]
Bit I like the Idea of the first one  _finding OSM in Python_  better than the second  _finding Python in OSM_ .

**Comment by PhilippRigoll** [comment]
> 
> 
> Here is the answer:
> 
> Hi,
> 
> changes to the logo outline are not permitted, so you'd either have to place the additional graphics completely inside the two snakes or completely outside.
> 
> Thanks,

Thanks for asking! I think that's exactly the right way 👍

**Comment by PhilippRigoll** [comment]
> 
> 
> ![Icon suggestion v1](https://user-images.githubusercontent.com/46082330/83963137-f2829080-a8a3-11ea-8476-09580ccab14a.png)
> 
> Maybe something like that?

Awesome, I really like this one!

I get your point that it would be nicer if Python is editting the map... Hm. Maybe a snake drawing the map would be an idea. We need someone with drawing skills here :D

Nethertheless I like your suggestion.

**Comment by thefeiter** [comment]
Yep, drawin skills required. Mine would not be sufficient. I will ask a few people...
Should we again ask for permission and use this one for now?

**Comment by PhilippRigoll** [comment]
Have you already asked? From the OSM point of view this shouldn't be a problem because this is an editor.

**Comment by thefeiter** [comment]
I just did it. Had no time over the last days ;)

**Comment by thefeiter** [comment]
I got an answer!!!

Hi Marvin,

thanks. We can approve this version.

If you want to make it even better, please add a thin outset outline around the logo to separate it from the background some more.

Thanks,

**Comment by PhilippRigoll** [comment]
Nice :) Don't get me wrong. My intension was not to hustle you.

**Comment by thefeiter** [comment]
Thats fine!

**Comment by PhilippRigoll** [comment]
> I got an answer!!!
> 
> Hi Marvin,
> 
> thanks. We can approve this version.
> 
> If you want to make it even better, please add a thin outset outline around the logo to separate it from the background some more.
> 
> Thanks,

Okay. Sounds doable, what do you think?

**Comment by thefeiter** [comment]
Yep, but I did not really get what he means ba outset outline...
![Icon suggestion v1 1](https://user-images.githubusercontent.com/46082330/84387346-25ee5380-abf3-11ea-9e3e-375df24421d0.png)
Something like this?

**Comment by thefeiter** [comment]
Maybe a drop shadow...

![Icon suggestion v1 2](https://user-images.githubusercontent.com/46082330/84388473-f2acc400-abf4-11ea-9be3-10fed8f1d509.png)

**Comment by thefeiter** [comment]
Heres a comparison:
![logo_mix](https://user-images.githubusercontent.com/46082330/84388838-841c3600-abf5-11ea-8067-a6fa963d59ce.png)

**Comment by PhilippRigoll** [comment]
Maybe a black outline?

**Comment by thefeiter** [comment]
I got approval for the dropshadow icon!!!
Can/should we somewhere archive the E-Mail traffic for later proof?

**Comment by PhilippRigoll** [comment]
:+1: Uh yeah! Thank you. 
Yes, we definitely should. Maybe just paste everything here as a comment?

**Comment by thefeiter** [comment]
Will do.

**Comment by thefeiter** [comment]
Here is my mail history with Marc-Andre Lemburg of the Python Software Foundation in which we got approval for our icon design.
<details><summary>Show E-Mail history</summary>

Hi Marvin,

that works as well. The outset outline would look like this:
![grafik](https://user-images.githubusercontent.com/46082330/84480642-2c350c00-ac95-11ea-9287-4fc6ca0ab320.png)


You can create this, but using the logo SVG, copying the logo, with both instances on top of each other and adding a thicker white outline to background one:

![grafik](https://user-images.githubusercontent.com/46082330/84480632-293a1b80-ac95-11ea-9ada-409ef7fdb505.png)



On 11.06.2020 16:00, thefeiter wrote:
> Hi,
>
> very good! I dont really understand what you men by outset outline. (since I am not a native english speaker)
> But maybe a drop shadow like this looks good to you?
>![grafik](https://user-images.githubusercontent.com/46082330/84480621-217a7700-ac95-11ea-9cb4-afbbed89ea55.png)

>
>
> Thanks,
>
> Marvin
>
> Am 11.06.20 um 12:32 schrieb M.-A. Lemburg:
>> Hi Marvin,
>>
>> thanks. We can approve this version.
>>
>> If you want to make it even better, please add a thin outset outline around the logo to separate it from the background some more.
>>
>> Thanks,
>> -- 
>> Marc-Andre Lemburg
>> Python Software Foundation
>> http://www.python.org/psf/
>> http://www.malemburg.com/
>>
>>
>> On 11.06.2020 10:49, thefeiter wrote:
>>> Hi,
>>>
>>> would this be permitted? Since the outline of the logo is kept:
>>>![grafik](https://user-images.githubusercontent.com/46082330/84480605-17f10f00-ac95-11ea-9392-45168ecfe863.png)

>>>
>>>
>>> Thanks,
>>>
>>> Marvin
>>>
>>>
>>> Am 06.06.20 um 23:39 schrieb M.-A. Lemburg:
>>>> Hi Marvin,
>>>>
>>>> changes to the logo outline are not permitted, so you'd either have to place the additional graphics completely inside the two snakes or completely outside.
>>>>
>>>> Thanks,
>>>> -- 
>>>> Marc-Andre Lemburg
>>>> Python Software Foundation
>>>> http://www.python.org/psf/
>>>> http://www.malemburg.com/
>>>>
>>>>
>>>> On 06.06.2020 23:19, thefeiter wrote:
>>>>> To whom it may concern,
>>>>>
>>>>> I am involved in working on a Python based editor for OpenStreetMap data. We want to choose an icon for our application wich is a mixture of the original Python logo and the original OpenStreetMap logo.
>>>>> Our Idea is, to create something like this:
>>>>>
>>>>>![grafik](https://user-images.githubusercontent.com/46082330/84480555-0576d580-ac95-11ea-8ee6-1ac61c24524d.png)

>>>>>
>>>>> I am not sure, if this violates your trademark policy or not.
>>>>>
>>>>> I am looking forward to a clarification on that topic.
>>>>>
>>>>> Regards
>>>>>
>>>>> Marvin Feiter
>>>>>
>>>>> _______________________________________________
>>>>> psf-trademarks mailing list
>>>>> psf-trademarks@python.org
>>>>>
>>>>> Wiki: http://wiki.python.org/psf/TrademarksCommittee/
>>>>> List: https://mail.python.org/mailman/listinfo/psf-trademarks
>>>>
>>>
>>
>

-- 
Marc-Andre Lemburg
Python Software Foundation
http://www.python.org/psf/
http://www.malemburg.com/

</details>

**Comment by thefeiter** [comment]
Can't this be closed?

**Comment by PhilippRigoll** [comment]
Yes, you are right
