### ISSUE TITLE
Cannot identify image file

### ISSUE THREAD

**Issue by thefeiter** [PhilippRigoll/Osmapy#19]
when running in Terminal I am getting the error (memory adress changing with each error)
```Error: cannot identify image file <_io.BytesIO object at 0x7fc06003c3b8>```
loads of times. Doesn't seem to cause problems, but I think this shouldn't be like that.

I was not yet able to find out where it comes from.

**Comment by PhilippRigoll** [comment]
Yes. I think #7 could fix this.
