### ISSUE TITLE
Possibility to disable tileserver in the layer manager

### ISSUE THREAD

**Issue by PhilippRigoll** [PhilippRigoll/osmapy#23]
The disabled tileserver shouldn't be loaded and rendered. That way we can gain speed. Tilemaps could be disabled by default using a flag in the config file.

**Comment by thefeiter** [comment]
Disabling in config is possible via #26 
One could now add tickboxes to the layers in the manager. Didn't find out how yet...

**Comment by PhilippRigoll** [comment]
I changed it a bit. The tiles are loaded but not shown now. At least in my tests the drawing of many tiles slowed down the process and not the loading in the background.
I also added a checkbox in the layer manager.

**Comment by thefeiter** [comment]
That is working great! Is there a specific reason not to put the checkboxes in the list of Layers?

**Comment by PhilippRigoll** [comment]
No. There is not. The QListWidget what is used for the LayerManager supports drag'n'drop of the layers. And is was the easiest solution that came to my mind. This could/should be improved!
