### ISSUE TITLE
Check the config file while loading

### ISSUE THREAD

**Issue by PhilippRigoll** [PhilippRigoll/osmapy#27]
Check the config file to prevent errors when something is missing  or wrong (e.g. #24). Notfiy the user what is wrong.

**Comment by thefeiter** [comment]
Should we improve the Error Message output?

**Comment by thefeiter** [comment]
I did not find a prettier way of outputting the `v.errors` since it is a mixture of `dicts, and lists.

**Comment by PhilippRigoll** [comment]
I think the json.dumps function could help here.

https://docs.python.org/3.8/library/json.html
