### ISSUE TITLE
Only load tiles which exist

### ISSUE THREAD

**Issue by PhilippRigoll** [PhilippRigoll/Osmapy#7]
At the moment there is no check if a tile exists. Everything is loaded.
As described [here](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) only tiles with X from 0 to 2^zoom − 1 and Y from 0 to 2^zoom -1 can exist.

Maybe one can also implement that the user cannot leave the world.

**Comment by thefeiter** [comment]
Prevent Leaving the world: #21
